### ISSUE TITLE
Give me results in a more compact way

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/Prime-factorization#1]
Instead of returning a list of prime #s, can you say something like:

36= = 2^3 * 3^2 * 5^1

**Comment by jybluekim** [comment]
I meant 180 = 2^3 * 3^2 * 5^1

**Comment by jybluekim** [comment]
You cannot just close an issue. That way, you get an unhappy customer! Ask for a suggestion - maybe the requester can do the fix himself. Be creative.

**Comment by ajkim0630** [comment]
you can fix it! :(

**Comment by jybluekim** [comment]
I fixed and committed.
